### PR TITLE
Refactors (including optparse → argparse), and add long options

### PR DESCRIPTION
**Pull request by vergenzt**
Hi! I had fun with this one. 🙂 Let me know if you prefer that I break out separate PRs for the individual refactor commits. I kept them in one PR for now since the "business value" for the first two isn't as clear until you get to the point of adding long options (where using `snake_case` gets you a free implicit `dest` parameter). Though IMO the majority of the value is in consistency with broader Python ecosystem conventions.

(Which, admittedly, is funny to see alongside the `camelCase` API for the aging `unittest` module. 🤦🏻‍♂️ I still think it's worth using `snake_case` overall outside of those API calls tho, personally.)

If you object to any part of this that's totally fine - I had fun and learned a bunch doing these so the effort wasn't wasted regardless. 🙂 I'm happy to make any changes you prefer. I made a few executive decisions along the way, any of which you, as the maintainer, are of course welcome to disagree with and request changes to.

### CODE REVIEW

**Comment by nedbat** [comment]
Wow, this is a lot.  I know how these kind of refactors go, they kind of snowball.  It would be easier to review in smaller pieces, but that might not be possible.

**Comment by vergenzt** [comment]
Yeah sorry for the shock! It's currently split up commit-by-commit, but I can split it into separate PRs for ease of review 👌

**Comment by vergenzt** [comment]
Closing in favor of separate PRs

**Comment by vergenzt** [comment]
Followup PRs are going to be

- https://github.com/nedbat/cog/compare/main...vergenzt:cog:gh-32-remove-hungarian
- https://github.com/vergenzt/cog/compare/gh-32-remove-hungarian...gh-32-camel-to-snake-case
- https://github.com/vergenzt/cog/compare/gh-32-camel-to-snake-case...gh-32-refactor-optparse-to-argparse
- https://github.com/vergenzt/cog/compare/gh-32-refactor-optparse-to-argparse...gh-32-add-option-long-forms

**Pull request closed without merging**
